In [53]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
import os
os.listdir()
#Pour import son module (contenant ses classes), le mettre dans fichier.txt,
#renommer en fichier.py
#import nomfichier: example: zoo.py: import zoo
#from zoo import Animal: 
#chien = Animal(2,4,10)

['multithreading_Selenium_Arnaud_v2.ipynb',
 '20190718_Programmation_Oriente_Objet.ipynb',
 'multithreading.ipynb',
 '20190417 Introduction à la programmation python .ipynb',
 'derivees.ipynb',
 'train.csv',
 '.ipynb_checkpoints',
 'classes_automatisationML_Arnaud.ipynb',
 '20190712_operators_exercice_et_autres.ipynb']

In [60]:
class Auto_ml:
    def __init__(self,nom_fichier,colonne_prediction):
        self.fichier=nom_fichier
        self.dataset=pd.read_csv(self.fichier)
        self.colonne_prediction=colonne_prediction
        self.y=self.dataset[self.colonne_prediction].values
    
    def predict(self):
        self.X_train, self.X_test, self.y_train, self.y_test = self.X()
        
        classifier_linear = LinearRegression()
        classifier_linear.fit(self.X_train, self.y_train)
        
        predicted_linear = classifier_linear.predict(self.X_test)
        scoreLinear = r2_score(self.y_test,predicted_linear)
        
        classifier_regression = LogisticRegression()
        classifier_regression.fit(self.X_train,self.y_train)
        
        predicted_regression = classifier_regression.predict(self.X_test)
        scoreLogistic = r2_score(self.y_test,predicted_regression)
        
        return "accuracy lineaire:",scoreLinear,"accuracy regression:",scoreLogistic
        
      
    def _pre_processing(self):
        #drop la colonne prédite
        #To delete the column without having to reassign df you can do:
     
        X = self.dataset.loc[:,"Id":"SaleCondition"]
        #Traiter les NA
         # making new data frame with dropped NA values for column with all values missing
        #col =  "MSSubClass"
        #np.isnan(df[col]).count()
        
        #Drop columns qui ont 25% de donnée manquantes
        X.dropna(axis='columns', thresh=0.75 * len(X), inplace= True)
        
        # Get dummies
        X = pd.get_dummies(X, prefix_sep='_', drop_first=True)
       
        #for col in self.dataset.columns:
            #if np.isnan(self.dataset[col]).count > float(np.isnan(self.dataset[col])).count * 0.75:
                #self.dataset[col] = self.dataset.dropna(subset=[col],axis = 1, how ='all')
            #else:
               # self.dataset[col] = self.dataset.dropna(subset=[col],axis = 1, how ='any')
                
        imp_mean = IterativeImputer(random_state=0)
        imp_mean.fit(X)
        X = imp_mean.fit_transform(X)
        X = pd.DataFrame(X)
        
        #Réduction dimensions
        data_columns = X.columns
        for x in data_columns:
            if X[x].dtypes == "float64":
                X[x] = X[x].astype('float32')
            if X[x].dtypes == "int64":
                X[x] = X[x].astype('int32')
         
        '''
      
        #imputer = Imputer(missing_values="NaN", strategy = 'mean')
        # L'objet imputer n'est pas encore lié à x. Pour lier :
        #imputer.fit(self.dataset)
        # Puis remplacer les valeurs
        #self.dataset = imputer.transform(self.dataset)    
            
        #Réduction dimensions
        #data_columns = self.dataset.columns
        #for x in data_columns:
            #if self.dataset[x].dtypes == "float64":
             #   self.dataset[x] = self.dataset[x].astype('float32')
            #if self.dataset[x].dtypes == "int64":
             #   self.dataset[x] = self.dataset[x].astype('int32')
            #if self.dataset[x].dtypes == "object":
                #self.dataset[x] = self.dataset[x].astype('category')
                
        #Label et onehotencoder
         #df_cat = df.astype('category')
         #df_cat.dtypes
        
        '''
     
        '''
        for col in self.dataset.columns:
          
            if self.dataset[col].dtypes == 'object':
                
                labelencoder_X = LabelEncoder()
                self.dataset[col] = labelencoder_X.fit_transform(self.dataset[col])
               
                pos = self.dataset.columns.get_loc(col)
                pos = int(pos)
               
                onehotencoder = OneHotEncoder(categorical_features = [pos])
                self.dataset = onehotencoder.fit_transform(self.dataset).toarray()
        '''
        '''
        imputer = Imputer(missing_values="NaN", strategy = 'mean')
        # L'objet imputer n'est pas encore lié à x. Pour lier :
        imputer.fit(self.dataset)
        # Puis remplacer les valeurs
        self.dataset[col] = imputer.transform(self.dataset)
        '''  
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X,self.y, test_size = 0.2, random_state = 0)

        sc = StandardScaler()
        self.X_train = sc.fit_transform(self.X_train)
        self.X_test = sc.transform(self.X_test)
        return self.X_train,self.X_test,self.y_train,self.y_test
    
    def X(self):
        return self._pre_processing()
    
    def y(self):
        return y

In [61]:
auto_data = Auto_ml("train.csv","SalePrice")
#retourn un X qui a été prétraité
auto_data.X()

(array([[-0.28399978, -0.86836547,  0.86631708, ..., -0.10188534,
         -2.20665963,  3.30429529],
        [ 0.31396549, -0.86836547, -0.46759368, ..., -0.10188534,
          0.45317365, -0.30263639],
        [-1.53213363, -0.63114155,  0.42168016, ..., -0.10188534,
          0.45317365, -0.30263639],
        ...,
        [ 1.13498129,  0.79220197, -0.11188415, ..., -0.10188534,
          0.45317365, -0.30263639],
        [-0.42399958,  1.50387373, -1.04826327, ..., -0.10188534,
          0.45317365, -0.30263639],
        [-0.12738983,  0.08053021, -0.55652106, ..., -0.10188534,
          0.45317365, -0.30263639]]),
 array([[-0.49518592, -0.86836547,  0.90316809, ..., -0.10188534,
         -2.20665963, -0.30263639],
        [-0.58535529, -0.15669371,  0.37721647, ..., -0.10188534,
          0.45317365, -0.30263639],
        [-0.66128739, -0.15669371,  0.1335122 , ..., -0.10188534,
          0.45317365, -0.30263639],
        ...,
        [ 1.54074343, -0.15669371, -0.46759368, ...,  

In [48]:
auto_data.y

array([208500, 181500, 223500, ..., 266500, 142125, 147500])

In [62]:
auto_data.predict()

/Users/arnaudbaleh/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/arnaudbaleh/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


('accuracy lineaire:',
 -1.8371602379228437e+22,
 'accuracy regression:',
 0.27460170045991794)

In [4]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [16]:
#La variable à prédire est la dernière colonne pour ce dataset
y = df.iloc[:, -1].values
print(y)

[208500 181500 223500 ... 266500 142125 147500]


In [17]:
df.shape

(1460, 81)

In [18]:
col =  "MSSubClass"
np.isnan(df[col]).count()

1460

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [ ]:
auto_data.y   # retourn le y
auto_data.predict()
auto_data.get_ypred('test.csv')
save_ypred.get_ypred('test.csv')

#***********************************

In [27]:
print(type(df_objet_pre))

<class 'pandas.core.frame.DataFrame'>


In [28]:
df_objet_pre.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [29]:
df_objet_pre.shape

(1460, 81)

In [28]:
data = df

In [29]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [19]:
data["LotArea"] = data["LotArea"].astype('int32')

In [28]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [20]:
data["LotFrontage"].astype('float32')
if data["LotArea"].dtypes == "int32":
    print("ok")

ok


In [38]:
d = {'col1': [1, 2], 'col2': [3, 4], 'col3': [3.7, 4.6]}
data_essai = pd.DataFrame(data=d)
data_essai.dtypes

col1      int64
col2      int64
col3    float64
dtype: object

In [45]:
listdata = data_essai.columns
for x in listdata:
    if data_essai[x].dtypes == "int64":
        data_essai[x].astype('int32')

In [46]:
data_essai.dtypes

col1      int64
col2      int64
col3    float64
dtype: object

In [11]:
data_col = data.columns
i = 0
while i < len(data_col):
    if data.iloc[:,i].dtypes == "object":
        data.iloc[:,i].astype("category")
    i+= 1

In [12]:
data.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley             object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
                  ...   
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
FireplaceQu       object
GarageType        object
GarageYrBlt      float64


In [30]:
#parcourir le data
data_columns = data.columns
for x in data_columns:
    
    if data[x].dtypes == "float64":
        data[x] = data[x].astype('float32')
    if data[x].dtypes == "int64":
        data[x] = data[x].astype('int32')
    if data[x].astype == "object":
        data[x].astype('category')

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int32
MSSubClass       1460 non-null int32
MSZoning         1460 non-null object
LotFrontage      1201 non-null float32
LotArea          1460 non-null int32
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int32
OverallCond      1460 non-null int32
YearBuilt        1460 non-null int32
YearRemodAdd     1460 non-null int32
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [ ]:
if data.dtypes == "float64":
    data = data.astype('float32')
if data.dtypes == "int64":
    data.dataset = data.astype('int32')
if data.dataset.dtypes == 'object':
    data.dataset.astype('category')

In [37]:
listdata = data.columns
for x in listdata:
    if data[x].dtypes == "int64":
        data.astype('int32')

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int32
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [23]:
for i in range(0,len(data)):
    if data[i].dtypes == "int64":
        x.astype('int32')

KeyError: 0

In [ ]:
data.info()