In [53]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
import os
os.listdir()
#Pour import son module (contenant ses classes), le mettre dans fichier.txt,
#renommer en fichier.py
#import nomfichier: example: zoo.py: import zoo
#from zoo import Animal: 
#chien = Animal(2,4,10)

['multithreading_Selenium_Arnaud_v2.ipynb',
 '20190718_Programmation_Oriente_Objet.ipynb',
 'multithreading.ipynb',
 '20190417 Introduction à la programmation python .ipynb',
 'derivees.ipynb',
 'train.csv',
 '.ipynb_checkpoints',
 'classes_automatisationML_Arnaud.ipynb',
 '20190712_operators_exercice_et_autres.ipynb']

In [60]:
class Auto_ml:
    def __init__(self,nom_fichier,colonne_prediction):
        self.fichier=nom_fichier
        self.dataset=pd.read_csv(self.fichier)
        self.colonne_prediction=colonne_prediction
        self.y=self.dataset[self.colonne_prediction].values
    
    def predict(self):
        self.X_train, self.X_test, self.y_train, self.y_test = self.X()
        
        classifier_linear = LinearRegression()
        classifier_linear.fit(self.X_train, self.y_train)
        
        predicted_linear = classifier_linear.predict(self.X_test)
        scoreLinear = r2_score(self.y_test,predicted_linear)
        
        classifier_regression = LogisticRegression()
        classifier_regression.fit(self.X_train,self.y_train)
        
        predicted_regression = classifier_regression.predict(self.X_test)
        scoreLogistic = r2_score(self.y_test,predicted_regression)
        
        return "accuracy lineaire:",scoreLinear,"accuracy regression:",scoreLogistic
        
      
    def _pre_processing(self):
        #drop la colonne prédite
        #To delete the column without having to reassign df you can do:
     
        X = self.dataset.loc[:,"Id":"SaleCondition"]
        #Traiter les NA
       
        
        #Drop columns qui ont 25% de donnée manquantes
        X.dropna(axis='columns', thresh=0.75 * len(X), inplace= True)
        
        # Get dummies
        X = pd.get_dummies(X, prefix_sep='_', drop_first=True)
       
                
        imp_mean = IterativeImputer(random_state=0)
        imp_mean.fit(X)
        X = imp_mean.fit_transform(X)
        X = pd.DataFrame(X)
        
        #Réduction dimensions
        data_columns = X.columns
        for x in data_columns:
            if X[x].dtypes == "float64":
                X[x] = X[x].astype('float32')
            if X[x].dtypes == "int64":
                X[x] = X[x].astype('int32')
         
         
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X,self.y, test_size = 0.2, random_state = 0)

        sc = StandardScaler()
        self.X_train = sc.fit_transform(self.X_train)
        self.X_test = sc.transform(self.X_test)
        return self.X_train,self.X_test,self.y_train,self.y_test
    
    def X(self):
        return self._pre_processing()
    
    def y(self):
        return y

In [61]:
auto_data = Auto_ml("train.csv","SalePrice")
#retourn un X qui a été prétraité
auto_data.X()

(array([[-0.28399978, -0.86836547,  0.86631708, ..., -0.10188534,
         -2.20665963,  3.30429529],
        [ 0.31396549, -0.86836547, -0.46759368, ..., -0.10188534,
          0.45317365, -0.30263639],
        [-1.53213363, -0.63114155,  0.42168016, ..., -0.10188534,
          0.45317365, -0.30263639],
        ...,
        [ 1.13498129,  0.79220197, -0.11188415, ..., -0.10188534,
          0.45317365, -0.30263639],
        [-0.42399958,  1.50387373, -1.04826327, ..., -0.10188534,
          0.45317365, -0.30263639],
        [-0.12738983,  0.08053021, -0.55652106, ..., -0.10188534,
          0.45317365, -0.30263639]]),
 array([[-0.49518592, -0.86836547,  0.90316809, ..., -0.10188534,
         -2.20665963, -0.30263639],
        [-0.58535529, -0.15669371,  0.37721647, ..., -0.10188534,
          0.45317365, -0.30263639],
        [-0.66128739, -0.15669371,  0.1335122 , ..., -0.10188534,
          0.45317365, -0.30263639],
        ...,
        [ 1.54074343, -0.15669371, -0.46759368, ...,  

In [48]:
auto_data.y

array([208500, 181500, 223500, ..., 266500, 142125, 147500])

In [ ]:
auto_data.predict()